"""
===============================================================================
COGNITIVE LLM & MULTIMODAL INFERENCE GATEWAY
===============================================================================

Architectural Overview:
-----------------------
This gateway provides a decoupled abstraction layer for natural language 
synthesis, high-tier Bloom's taxonomy generation, semantic evaluation, 
and dense vector embedding generation.

Supports:
1. Native Local Execution via Ollama (Zero-cloud latency, privacy-preserving)
2. Cloud Inference via Azure OpenAI (Scalable enterprise LLM deployment)

Diagram: Inference Routing Pipeline
-----------------------------------
```
 +------------------------+
 | Cognitive Service Call |
 +-----------+------------+
             |
             v
 +------------------------+
 | BaseInferenceGateway   |
 +-----------+------------+
             |
   +---------+---------+
   | (LLM_PROVIDER)    |
   v                   v
+-----------------+ +--------------------+
| OllamaGateway   | | AzureOpenAIGateway |
| (Local Native)  | | (Cloud API)        |
+--------+--------+ +---------+----------+
         |                    |
         v                    v
  [HTTP :11434]        [HTTPS Azure]
```

Academic Citations:
-------------------
- Touvron, H., et al. (2023). "Llama 2: Open Foundation and Fine-Tuned Chat Models." 
  arXiv preprint arXiv:2307.09288.
- Brown, T., et al. (2020). "Language Models are Few-Shot Learners." 
  Advances in Neural Information Processing Systems (NeurIPS 2020), 33, 1877-1901.
- Nussbaum, Z., et al. (2024). "Nomic Embed: Training a Reproducible Long Context 
  Text Embedder." arXiv preprint arXiv:2402.01613.
"""

from __future__ import annotations
import json
import logging
from abc import ABC, abstractmethod
from typing import AsyncIterator, Sequence
import httpx
from openai import AsyncAzureOpenAI
from app.core.cognitive_config import cognitive_settings

logger = logging.getLogger("superlearn.llm_gateway")


class BaseInferenceGateway(ABC):
    """
    Abstract Base Class establishing the standard contract for cognitive 
    language generation and semantic embedding services.
    """

    @abstractmethod
    async def generate_response(
        self,
        prompt: str,
        system_instruction: str = "",
        temperature: float = 0.7,
    ) -> str:
        """
        Synthesize a natural language completion from a given prompt and system directive.

        Args:
            prompt: User-facing prompt or pedagogical task instruction.
            system_instruction: High-priority system prompt establishing cognitive role/persona.
            temperature: Sampling temperature controlling entropy and creativity (0.0 to 1.0).

        Returns:
            Sanitized text completion generated by the underlying model.
        """
        ...

    @abstractmethod
    async def compute_embedding(self, text: str) -> list[float]:
        """
        Project textual passages into a continuous high-dimensional vector space.

        Formula:
            Let f_theta(t) be the embedding neural network parameterized by theta.
            vec(e) = f_theta(t) in R^d, where d is the vector dimension (e.g., d=768).

        Args:
            text: Arbitrary natural language text passage.

        Returns:
            Dense float vector of dimensionality specified by vector_dimension setting.
        """
        ...

    @abstractmethod
    async def stream_response(
        self,
        prompt: str,
        system_instruction: str = "",
        temperature: float = 0.7,
    ) -> AsyncIterator[str]:
        """
        Asynchronously stream generated tokens for real-time pedagogical feedback.

        Yields:
            Incremental text tokens as they arrive from the inference engine.
        """
        ...


class OllamaLocalInferenceGateway(BaseInferenceGateway):
    """
    Pure Python Native HTTP client for local Ollama daemon execution.
    Eliminates external cloud dependencies and Docker overhead.
    """

    def __init__(self) -> None:
        self.base_url: str = cognitive_settings.ollama_base_url.rstrip("/")
        self.chat_model: str = cognitive_settings.ollama_model
        self.embedding_model: str = cognitive_settings.ollama_embed_model
        self.timeout: float = cognitive_settings.ollama_request_timeout

    async def generate_response(
        self,
        prompt: str,
        system_instruction: str = "",
        temperature: float = 0.7,
    ) -> str:
        """
        Execute synchronous chat completion against local Ollama REST endpoint.
        """
        messages = []
        if system_instruction.strip():
            messages.append({"role": "system", "content": system_instruction})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.chat_model,
            "messages": messages,
            "stream": False,
            "options": {"temperature": temperature},
        }

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            try:
                response = await client.post(f"{self.base_url}/api/chat", json=payload)
                response.raise_for_status()
                data = response.json()
                return data.get("message", {}).get("content", "").strip()
            except httpx.HTTPError as exc:
                logger.error(f"Ollama inference error: {exc}")
                raise RuntimeError(
                    f"Local Ollama inference failed at {self.base_url}. Ensure Ollama is running (`ollama serve`). Error: {exc}"
                ) from exc

    async def compute_embedding(self, text: str) -> list[float]:
        """
        Compute dense vector representation using local Ollama embedding endpoint.
        """
        payload = {
            "model": self.embedding_model,
            "prompt": text,
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            try:
                response = await client.post(f"{self.base_url}/api/embeddings", json=payload)
                response.raise_for_status()
                data = response.json()
                embedding = data.get("embedding", [])
                if not embedding:
                    raise ValueError(f"Ollama returned empty embedding for model {self.embedding_model}")
                return embedding
            except httpx.HTTPError as exc:
                logger.error(f"Ollama embedding computation error: {exc}")
                raise RuntimeError(
                    f"Ollama embedding failed. Ensure model '{self.embedding_model}' is pulled (`ollama pull {self.embedding_model}`). Error: {exc}"
                ) from exc

    async def stream_response(
        self,
        prompt: str,
        system_instruction: str = "",
        temperature: float = 0.7,
    ) -> AsyncIterator[str]:
        """
        Stream token chunks from local Ollama endpoint via JSON-ND protocol.
        """
        messages = []
        if system_instruction.strip():
            messages.append({"role": "system", "content": system_instruction})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.chat_model,
            "messages": messages,
            "stream": True,
            "options": {"temperature": temperature},
        }

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            async with client.stream("POST", f"{self.base_url}/api/chat", json=payload) as response:
                response.raise_for_status()
                async for raw_line in response.aiter_lines():
                    if raw_line.strip():
                        try:
                            chunk = json.loads(raw_line)
                            token = chunk.get("message", {}).get("content", "")
                            if token:
                                yield token
                        except json.JSONDecodeError:
                            continue


class AzureOpenAIInferenceGateway(BaseInferenceGateway):
    """
    Enterprise Cloud Inference Gateway wrapping Azure OpenAI client.
    Activated dynamically when `LLM_PROVIDER=azure` is specified in environment.
    """

    def __init__(self) -> None:
        self.client = AsyncAzureOpenAI(
            azure_endpoint=cognitive_settings.azure_openai_endpoint,
            api_key=cognitive_settings.azure_openai_key,
            api_version=cognitive_settings.azure_openai_api_version,
        )
        self.deployment = cognitive_settings.azure_openai_deployment
        self.embed_deployment = cognitive_settings.azure_openai_embed_deployment

    async def generate_response(
        self,
        prompt: str,
        system_instruction: str = "",
        temperature: float = 0.7,
    ) -> str:
        messages = []
        if system_instruction.strip():
            messages.append({"role": "system", "content": system_instruction})
        messages.append({"role": "user", "content": prompt})

        response = await self.client.chat.completions.create(
            model=self.deployment,
            messages=messages,
            temperature=temperature,
        )
        return response.choices[0].message.content or ""

    async def compute_embedding(self, text: str) -> list[float]:
        response = await self.client.embeddings.create(
            model=self.embed_deployment,
            input=text,
        )
        return response.data[0].embedding

    async def stream_response(
        self,
        prompt: str,
        system_instruction: str = "",
        temperature: float = 0.7,
    ) -> AsyncIterator[str]:
        messages = []
        if system_instruction.strip():
            messages.append({"role": "system", "content": system_instruction})
        messages.append({"role": "user", "content": prompt})

        stream = await self.client.chat.completions.create(
            model=self.deployment,
            messages=messages,
            temperature=temperature,
            stream=True,
        )
        async for chunk in stream:
            token = chunk.choices[0].delta.content or ""
            if token:
                yield token


def create_inference_gateway() -> BaseInferenceGateway:
    """
    Factory method instantiating the appropriate inference gateway according 
    to the active configuration settings.
    """
    if cognitive_settings.llm_provider == "azure":
        logger.info("Initializing Azure OpenAI Inference Gateway.")
        return AzureOpenAIInferenceGateway()
    
    logger.info("Initializing Ollama Local Inference Gateway.")
    return OllamaLocalInferenceGateway()


# Global Singleton Gateway
llm_gateway: BaseInferenceGateway = create_inference_gateway()
